### ISSUE TITLE
Hey Developers 👋 Reply this message 

### ISSUE THREAD

**Issue by simpleneeraj** [asmblah/dynamic#16]
I am here because I need this package name for my package `dynamic` 

I am not be able to upload my dynamic npm package with this name.

What my package worked ?

My npm package based on Nextjs dynamic import here user can import components and library dynamically. 

Can you help me to give me this package name by deleting your package,  before you delete, download your package code.

**Comment by asmblah** [comment]
@simpleneeraj, I'm afraid this package is in use and so I won't be deleting it.

Thanks
